version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run build
      - run:
          name: Generate images
          command: yarn gen-images
          no_output_timeout: 1h
      - run:
          name: Gatsby Build
          command: ./node_modules/.bin/gatsby build
          no_output_timeout: 30m